### PR TITLE
dependencies updated

### PR DESCRIPTION
**Pull request by priyanshu0405**
Fixes Issue #56 
All the dependencies have been updated apart from the ones whose newer version are above than the semver requirements of the project. Updating them might break the code. 

elm

### CODE REVIEW

**Comment by Razzeee** [comment]
Hey there, you do seem to have some files too many. Seems like our gitignore is missing entries for `.cache` and `dist`?

**Comment by priyanshu0405** [comment]
Hey @Razzeee , updated my PR. Please have a look.

**Comment by Razzeee** [comment]
While I think it's fine to merge this, I don't think it addresses the linked issue, as the elm dependencies in the elm.json remain untouched

**Comment by priyanshu0405** [comment]
Hey @Razzeee updated elm.json, please have a look. Googled a lot but could not find anything so had to check every dependency individually and re-install the deprecated ones. Is there any better way? Thanks.

e

**Comment by Razzeee** [comment]
Check https://github.com/zwilias/elm-json

**Comment by priyanshu0405** [comment]
@Razzeee , please have a look. Did it using elm-json package.

**Comment by Razzeee** [comment]
LGTM, thank you!

**Pull request merged**
