### PR TITLE
Implemented change of theme upon switching of tabs (Rightsidebar)

### PR DESCRIPTION
**Pull request by developingright**
Hi @razzeee ,
I have implemented the #95 issue. Please let me know if any changes are required.

|   | Kodi Tab  | Local Tab |
| ------------- | ------------- | ------------- |
| Chorus | Chorus2(1) | Chorus2 |
| Elm Chorus | elm(1) |  elm |

### CODE REVIEW

**Comment by razzeee** [comment]
can you rebase this?

**Comment by developingright** [comment]
Sure, I will rebase this PR.

**Comment by razzeee** [comment]
That's a problem. Please do an `interactive` rebase and take some time to learn what/how to do that. It's pretty essential for your work/open source.

I would expect the rebase to drop the already merged commits and the commit message of the latest commit needs fixing.

**Comment by developingright** [comment]
Hi @razzeee,
I have rebased the PR once again and hopefully, it's right this time as there aren't any already merged commits.

**Comment by razzeee** [comment]
Perfect thanks

**Pull request merged**
