### PR TITLE
Elm Spa updated 

### PR DESCRIPTION
**Pull request by Kunal-8789**
Hey @razzeee, I have updated the Elm Spa to latest version  #65 

Screenshot 2022-03-21 211508

### CODE REVIEW

**Comment by razzeee** [comment]
I also think you need to update the npm dependency in tandem

**Comment by Kunal-8789** [comment]
> I also think you need to update the npm dependency in tandem

Hey @razzeee, Thanks for the inputs.
I have doubts regarding your comment "update the npm dependency in tandem".
Do you mean to update dev dependencies in package.json?
upgrading them breaks the code and then will need to fix the code in every page according to this official repo [Link](https://github.com/ryannhg/elm-spa-realworld/pull/2).
Screenshot 2022-03-24 034812
 Please guide me in this regard, if I interpreted you right or wrong.

**Comment by razzeee** [comment]
Yes, you will need to upgrade that on every page.

**Comment by Kunal-8789** [comment]
Closing this PR as i am finding some difficulty in rebasing, will open a new PR for this issue.

**Pull request closed without merging**
