### PR TITLE
[WIP] CI: setup github actions

### PR DESCRIPTION
**Pull request by priyanshu0405**
I tried adding a CI pipeline for elm-chorus using https://github.com/JorelAli/setup-elm but it fails due to this https://github.com/priyanshu0405/elm-chorus/runs/2159286939. But it works fine locally. What could be the issue?

### CODE REVIEW

**Comment by Razzeee** [comment]
It seems like you need to run `npm run build:dev:elm` to generate that file, but the naming makes it seem like it might only be intended for dev time. Maybe @ionif made an error somewhere?

**Comment by ionif** [comment]
No idea what this error is, I haven't experimented with adding a CI pipeline before to be honest. Sorry I can't help more 😞

**Comment by Razzeee** [comment]
I asked around for an elm-spa-parcel project. Will compare this https://github.com/bigardone/elm-spa-parcel with what we have, whenever I find the time, hopefully unblocks this. @priyanshu0405 feel free to go ahead.

**Comment by Razzeee** [comment]
Can you try changing https://github.com/priyanshu0405/elm-chorus/blob/master/public/index.html#L13 to an absolute path? so "./public/main.js"?

**Comment by Razzeee** [comment]
I've updated your PR, it should work fine now.

**Comment by priyanshu0405** [comment]
@Razzeee yes it is working fine. Thanks.

**Pull request merged**
